steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/no-code-architects-toolkit', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/no-code-architects-toolkit']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'no-code-architects-toolkit'
      - '--image'
      - 'gcr.io/$PROJECT_ID/no-code-architects-toolkit'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '16Gi'
      - '--cpu'
      - '4'
      - '--cpu-boost'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '5'
      - '--timeout'
      - '300s'
      - '--set-env-vars'
      - 'API_KEY=${_API_KEY}'
      - '--set-env-vars'
      - 'GCP_BUCKET_NAME=${_GCP_BUCKET_NAME}'
      - '--set-env-vars'
      - 'STORAGE_PATH=GCP'

substitutions:
  _API_KEY: 'default-value-replace-in-console'
  _GCP_BUCKET_NAME: 'default-value-replace-in-console'

images:
  - 'gcr.io/$PROJECT_ID/no-code-architects-toolkit'