name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: no-code-architects-toolkit
  REGION: asia-southeast1
  IMAGE: asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/no-code-architects-toolkit/image:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GH_ACTIONS_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Build and Push Container
      run: |
        # Create repository if it doesn't exist (may fail if no permission, but that's okay if it already exists)
        gcloud artifacts repositories create no-code-architects-toolkit \
          --repository-format=docker \
          --location=${{ env.REGION }} \
          --description="Repository for no-code-architects-toolkit" || true
          
        # Configure Docker to use gcloud as a credential helper
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
        
        # Build and push the container
        docker build -t ${{ env.IMAGE }} .
        docker push ${{ env.IMAGE }}

    - id: deploy
      name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ env.SERVICE_NAME }}
        image: ${{ env.IMAGE }}
        region: ${{ env.REGION }}
        flags: >
          --allow-unauthenticated
          --memory=16Gi
          --cpu=4
          --cpu-boost
          --min-instances=0
          --max-instances=5
          --timeout=300s
        env_vars: >-
          API_KEY=${{ secrets.API_KEY }},
          GCP_BUCKET_NAME=${{ secrets.GCP_BUCKET_NAME }},
          STORAGE_PATH=GCP,
          GCP_SA_CREDENTIALS=${{ secrets.GCP_SA_KEY }}

    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}
