name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: no-code-architects-toolkit
  REGION: asia-southeast1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ env.SERVICE_NAME }}
        source: ./
        region: ${{ env.REGION }}
        flags: >
          --allow-unauthenticated
          --memory=16Gi
          --cpu=4
          --cpu-boost
          --min-instances=0
          --max-instances=5
          --timeout=300s
        env_vars: |
          API_KEY=${{ secrets.API_KEY }}
          GCP_BUCKET_NAME=${{ secrets.GCP_BUCKET_NAME }}
          GCP_SA_CREDENTIALS=${{ secrets.GCP_SA_KEY }}

    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}
